image: python:3.6

before_script:

  - echo -e "machine gitlab.com\nlogin gitlab-ci-token\npassword ${CI_JOB_TOKEN}" > ~/.netrc
  - mkdir ${HOME}/.ssh && chmod 700 ${HOME}/.ssh
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  # You need to add PRIVATE KEY for all submodules as a variable to this project pipelines
  - ssh-add <(echo "$SSH_DEPENDENCIES_KEY")
  # Assume that networks are configured properly and we can trust private ssh keys.
  - ssh-keyscan -H -p 10022 gitlab.com >> ${HOME}/.ssh/known_hosts
  - ssh-keyscan -H gitlab.com >> ${HOME}/.ssh/known_hosts
  - git submodule init
  - git submodule update

  - apt-get update -yq && apt-get install libenchant-dev -yq
  - pip install  --no-cache-dir -r requirements/dev.txt

test:
  script:
    - invoke check
